clear
tic
warning("off")

M = [];
M = RNN_PARAMETERS(M, 8, 2.8, 1, 1, 0.6158);
M = RNN_INITIALIZATION(M);
M = RNN_SIMULATION(M);
M = RNN_ANALYSIS(M);
M = RNN_GRAPHIC_PARAMETERS(M);
M = RNN_GRAPHICS(M);
M = RNN_DISPLAY(M);

toc