function M = RNN_DISPLAY(M)

T = table([M.f_E_mean; M.f_I_mean; M.f_mean], ...
          [M.CV_E_mean; M.CV_I_mean; M.CV_mean], ...
          'VariableNames',{'f (Hz)','CV (au)'},...
          'RowNames',{'Exc neurons';'Inh neurons';'All neurons'});
disp(T);

T = table([M.R_synchr_mean; M.rho_synchr], ...
          'VariableNames',{'Synchrony (au)'},...
          'RowNames',{'on correlations';'on variance'});
disp(T);
